---
jobs:
- name: build-library-ng
  plan:
  - aggregate:
    - get: library-ng
      trigger: true
    - get: library-ci
  - task: build
    file: library-ci/tasks/build-ng/task.yml

- name: build-library-backend
  plan:
  - aggregate:
    - get: library-backend
      trigger: true
    - get: library-ci
    - get: library-backend-version
      params: {pre: rc}
  - task: build
    file: library-ci/tasks/build-library-backend/task.yml
  - put: maven-milestone
    params:
      file: build-output/library-backend-*.jar
      version_file: library-backend-version/version
  - put: library-backend-version
    params:
      file: library-backend-version/version

resources:
- name: library-ng
  type: git
  source:
    uri: ((git-uri-library-ng))
    branch: ((git-branch-library-ng))
    private_key: ((git-private-key))

- name: library-backend
  type: git
  source:
    uri: ((git-uri-library-backend))
    branch: ((git-branch-library-backend))
    private_key: ((git-private-key))

- name: library-ci
  type: git
  source:
    uri: ((git-uri-library-ci))
    branch: ((git-branch-library-ci))
    private_key: ((git-private-key))

- name: library-backend-version
  type: semver
  source:
    driver: git
    uri: ((git-uri-library-backend))
    branch: version
    file: version
    initial_version: 1.0.0-rc.0
    private_key: ((git-private-key))

- name: maven-milestone
  type: maven-resource
  source:
    url: ((maven-milestone-url))
    artifact: io.pivotal:library-backend:jar
    username: ((maven-milestone-username))
    password: ((maven-milestone-password))
    skip_cert_check: ((maven-milestone-skip-ssl))

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest
