---
jobs:
- name: build-library-ng
  public: true
  plan:
  - aggregate:
    - get: library-ng
      trigger: true
    - get: library-ci
    - get: library-ng-version
      params: {pre: rc}
  - task: ng-build
    file: library-ci/tasks/build-ng/task.yml
    output_mapping: {build-output: ng-build-output}
    params:
      NG_TEST_BROWSERS: HeadlessChrome
      NG_TEST_CODE_COVERAGE: true
      NG_BUILD_ENVIRONMENT: prod
  - task: pack
    file: library-ci/tasks/tar/task.yml
    input_mapping: {build-input: ng-build-output}
    output_mapping: {build-output: pack-output}
    params:
      TAR_MODE: compress
      TAR_FILE: library-ng-*.tar.gz
  - put: maven-milestone-ng
    params:
      file: pack-output/library-ng-*.tar.gz
      version_file: library-ng-version/version
  - put: library-ng-version
    params:
      file: library-ng-version/version

- name: deploy-library-ng-test
  public: true
  plan:
  - aggregate:
    - get: library-ng
      passed: [build-library-ng]
    - get: maven-milestone-ng
      passed: [build-library-ng]
      trigger: true
    - get: library-ci
  - task: unpack
    file: library-ci/tasks/tar/task.yml
    input_mapping: {build-input: maven-milestone-ng}
    output_mapping: {build-output: dist}
    params:
      TAR_MODE: decompress
      TAR_FILE: library-ng-*.tar.gz
  - put: cf-test-library-ng
    params:
      commands:
      - command: create-org
      - command: create-space
      - command: push
        manifest: library-ng/manifest.yml
        app_name: ((cf-test-ng-appname))
        hostname: ((cf-test-ng-hostname))
        instances: 1
        path: dist

- name: build-library-backend
  public: true
  plan:
  - aggregate:
    - get: library-backend
      trigger: true
    - get: library-ci
    - get: library-backend-version
      params: {pre: rc}
  - task: build
    file: library-ci/tasks/build-library-backend/task.yml
  - put: maven-milestone
    params:
      file: build-output/library-backend-*.jar
      version_file: library-backend-version/version
  - put: library-backend-version
    params:
      file: library-backend-version/version

- name: deploy-library-backend-test
  public: true
  plan:
  - aggregate:
    - get: library-backend
      passed: [build-library-backend]
    - get: maven-milestone
      passed: [build-library-backend]
      trigger: true
  - put: cf-test-library-backend
    params:
      commands:
      - command: create-org
      - command: create-space
      - command: push
        manifest: library-backend/manifest.yml
        app_name: ((cf-test-appname))
        hostname: ((cf-test-hostname))
        instances: 1
        path: maven-milestone/library-backend-*.jar

resources:
- name: library-ng
  type: git
  source:
    uri: ((git-uri-library-ng))
    branch: ((git-branch-library-ng))
    private_key: ((git-private-key))

- name: library-ng-version
  type: semver
  source:
    driver: git
    uri: ((git-uri-library-ng))
    branch: version
    file: version
    initial_version: 1.0.0-rc.0
    private_key: ((git-private-key))

- name: library-backend
  type: git
  source:
    uri: ((git-uri-library-backend))
    branch: ((git-branch-library-backend))
    private_key: ((git-private-key))

- name: library-ci
  type: git
  source:
    uri: ((git-uri-library-ci))
    branch: ((git-branch-library-ci))
    private_key: ((git-private-key))

- name: library-backend-version
  type: semver
  source:
    driver: git
    uri: ((git-uri-library-backend))
    branch: version
    file: version
    initial_version: 1.0.0-rc.0
    private_key: ((git-private-key))

- name: maven-milestone
  type: maven-resource
  source:
    url: ((maven-milestone-url))
    artifact: io.pivotal:library-backend:jar
    username: ((maven-milestone-username))
    password: ((maven-milestone-password))
    skip_cert_check: ((maven-milestone-skip-ssl))

- name: maven-milestone-ng
  type: maven-resource
  source:
    url: ((maven-milestone-url))
    artifact: io.pivotal:library-ng:tar.gz
    username: ((maven-milestone-username))
    password: ((maven-milestone-password))
    skip_cert_check: ((maven-milestone-skip-ssl))

- name: cf-test-library-ng
  type: cf-cli-resource
  source:
    api: ((cf-test-api))
    username: ((cf-test-username))
    password: ((cf-test-password))
    skip_cert_check: false
    org: ((cf-test-org))
    space: ((cf-test-space))

- name: cf-test-library-backend
  type: cf-cli-resource
  source:
    api: ((cf-test-api))
    username: ((cf-test-username))
    password: ((cf-test-password))
    skip_cert_check: false
    org: ((cf-test-org))
    space: ((cf-test-space))

# - name: cf-uat-library-backend
#   type: cf-cli-resource
#   source:
#     api: https://run.pivotal.io
#     username: ((cf-uat-username))
#     password: ((cf-uat-password))
#     skip_cert_check: false
#     org: ((cf-uat-org))
#     space: ((cf-uat-space))

# - name: cf-prod-library-backend
#   type: cf-cli-resource
#   source:
#     api: https://run.pivotal.io
#     username: ((cf-prod-username))
#     password: ((cf-prod-password))
#     skip_cert_check: false
#     org: ((cf-prod-org))
#     space: ((cf-prod-space))

resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

- name: cf-cli-resource
  type: docker-image
  source:
    repository: pivotalpa/cf-cli-resource
    tag: latest
